### ISSUE TITLE
Exception: Access Denied

### ISSUE THREAD

**Issue by OD1995** [drippyer/ESPN_FF_Tool#2]
Great idea! But I think it may not work for private leagues?

I got:

```
Traceback (most recent call last):
  File "C:\Users\Oli\Documents\NFL\Scripts\espnTool.py", line 176, in <module>
    displayMenu()
  File "C:\Users\Oli\Documents\NFL\Scripts\espnTool.py", line 159, in displayMenu
    getScores()
  File "C:\Users\Oli\Documents\NFL\Scripts\espnTool.py", line 34, in getScores
    league = League(league_id, year)
  File "C:\Users\Oli\AppData\Local\Continuum\anaconda3\lib\site-packages\ff_espn_api\league.py", line 49, in __init__
    self._fetch_league()
  File "C:\Users\Oli\AppData\Local\Continuum\anaconda3\lib\site-packages\ff_espn_api\league.py", line 59, in _fetch_league
    checkRequestStatus(self.status)
  File "C:\Users\Oli\AppData\Local\Continuum\anaconda3\lib\site-packages\ff_espn_api\league.py", line 18, in checkRequestStatus
    raise Exception("Access Denied")
Exception: Access Denied
```

**Comment by drippyer** [comment]
You'd be correct as of right now, private leagues do not work at the moment. Another user has submitted a pull request that should fix this, I will be adding the capability soon!

**Comment by drippyer** [comment]
Private league capability has been added! Please feel free to update and open a new issue if you have any issues with the latest version
